const ELEVATIONS_BASE64 = "IwAjACkAMwA6AEIAUwBHAC0ARABVAGoAaQBiAFgAWgBfAGoAagBoAF4AVQBVAFUAVQBVAGUAgQB4AIEAnQDGAOAAIgAjADEAPQBBADUALQAtAE0AVQBdAGwAbABeAGsAZABjAGYAagBoAGUAdQB6AIEAhwCDAHsAWgBaAIkAwwDQAMsAJwAxADkAOwA8AC0ASwA2AD8ARABkAHkAaQBrAHQAawB1AGkAaAB0AHkAcAB6AIAAfwBoAGgAWgBaAH0AigCzALgAMAAzADcAPAA/AEsATQBSAEoAWABXAGwAZAB0AGsAZABnAG8AeABuAG0AgACCAHIAaAB6AIsApwC3AMcAzADXANcANQAxADgAOwA4AEoAUQBGAEwAZABZAFgAWQBiAFoAXABpAHsAcQBuAGgAbwB9AG0AeQCkAL8A0ADYAO8A+QAIARoBKwAyADsARABCAD8ASQBGAEgATQBVAFEAVgBVAFwAYwBiAFoAaABmAGcAcgBvAIsAqgDjAAQBCQEdATcBSgFCAWEBKAAnADgAQQBGAFAATQBNAEkARQBSAFUAXwBXAFoAXgBgAF0AXwBnAGQAbQCWALwA6gBQAWEBYwF7AagBmwGbAY8BMAApAEAARwBNAFMATgBTAEwASABXAGYAcgBlAFwAXgBaAFUAXQBNAFoAkwC/APkAUgG+Ad4B7gESAigCCwLUAdYBOwAtAE8ASgBJAEgARQBNAFsAVABfAGUAYwBXAE8AWgBVAEcARgBuAJAAxQD8AHIBwwElAk0CjQKyAo4CYwJjAk4COAAtADwAQQBGAD8AQQBKAFkAUwBaAFwAVABMAF0AXgBAAE4AaQCbANAAJgFlAeABRAKsAusCLQMkA/cC8gLHArICLgAyAEkAPwBHAEgAUwBTAFQARABhAGQAUABbAF4APgBKAG8AogDxAC0BrQH7AW8CtAJWA4EDkgN4A00DQgP9ArQCOgA6AEAARwBPAEsAWwBVAFMAVABaAFMASQA2ADQAZAB3ALEA3wA6AX0BGQKFAgADTAPBA+MD8QPhA4sDXgP+Ap8CNQA4AD4ARgBLAE8ASwBCAFQAYABJADoAJgAvAFYAggCjAPYAOgGQAdoBhwLuApgD1gMTBEcEKAT1A6ADaQPNAnACQABGAEkAUAA/AEAANwA4ADUAMwAxADEAPABbAIEAoADcAEoBmQETAnQC+AJwA/EDKwREBFYEIQTsA4QDLwOXAi0CTwBCAEYATAA5ADYAIwAgAAUABQAyAEYAhgCgAK4ABQFBAboBDAKPAuYCgQPSAykEagSCBF4E/wO1AzMDuQI6Av0BQwBKAEcAOQAxADcABQAFABMAJQBaAIgAwQD2AD0BmQHjAWICmQImA5MDGgReBIsEsQSDBCgEtQNeA7kCaQIDAs8BRgBBADkANwA3ACwABQAFACUAQgBNAGQAHQFnAbwBPQKOAvQCUwP6AzYEgwSnBLIEpwQrBMwDNgPlAnoCMwLEAZoBNgA5ADkANgATAAUABQAFADcAZACdAGIANAHwAT4CtAIBA7ADFAR9BKcEtgSaBGMEBgSRAyUDtAJuAiUC1AGbAYUBNQAwADkAPQAsAAUABQAFAFoAcQDWABsB5QE+An0CJwOQAycEggTLBM0EdAQ9BMEDgAP1ApMCLwLYAboBkwFtAWMBJAA7ACgAIAAFAAUABQAFAFQAhAD/AHgBAwJNAsECigMRBIYEtgSkBG4EIQTxAzED8AJPAgICsAGAAWkBRAFBAT8BOABDADMAKAAFAAUALQAwAFgAdgDqAD8B5gFlAuICkwPPA0UEeQRHBBwEwwNKA8ICdQLQAZoBWAE/ASEBHAEuAS8BRgA+ADoAVwBQADYARABFAFUAZgCEABYB1gFZAr4CAwNQA/ADEgTYA54DOQPMAlYCBgK5AW8B/gD0APsACAEiASABNAA7AF0AVwA/AEcAPgBPAGYAZgBtAKsAiAHyATgChQIGA3MDWQMyAwUDjAJMAgQCwAF5AVEB1wDSAOYACgEFAQsBPQBIAFQAVwBDAEYAbgBfAGIAWgBLAG0A9QCAAcEBOwKIAr0CrQKRAl0CDwLkAaABbwE0AQwBwwC8AOEA6ADuAPcAUwBgAF4AaQBlAFMAcgBpAF4ASwBLAIIA9QAWATcBvQHaAQACCAIGAtYBpAGJAVQBLAH6ANAAqwC1AM8A3ADmAOUAagBdAGgAcwBoAGgAYQBkAEsASwBmAKYA5gDxAPYASwFUAYYBgAF4AVUBRwEnAREBEQHQAKYAnQC7ANAA2QDgAPEAcgBxAHIAZwBkAF8AXgBZAHgAbQCHAKgAvgC/AMwA6gD6ABYBIAEaAQUBDAH2ANMAyQCnAIcAqAC/AMcA0QDhAPIAagBrAGoAZgBiAGIAbgBhAGgAbACLAKQAoQC5ALwAzwDbANAA0gDeAOkA3wDOAKAAmwCQAIQAqACsAMQAywDgAPQAbQBxAG4AbABrAHMAgQB4AHcAcwCGAIsAlAClALIAswCxALQAtgDNAMgAwQC3AJYAkQBuAHcAmAC1ALsAvwDhAAEBZwBiAHAAeQCLAI0AkwCQAIgAlgCGAI0AkgCYAKkApQClAKkArADBALwArwCsAIMAbwB2AJQAlwCpAMsA0wDpACQBYQBtAIgAjQCJAI8AmwCbAJAAkQCVAJEAkgCWAJkApACsALAArACwAKcAqQCWAGEAXgCRAI8AuQDJANgA+ABPAYYBbABzAH0AggCSAJ0AnQCqAJwAnACZAJYAoACbAK0AmwCpALgAtAClALYAowB7AFQAgwCLAJEA0QDcABwBagG9ARkCdAB4AIQAhACfALMApQCwAK4AqgCwAKQAoACgAKgArwCuAKgAqwC2ALIAfwBsAH4AfQCIAJUA5wAzAaAB2wFGAngC";

function decodeElevations(): number[] {
  const bytes = Uint8Array.from(atob(ELEVATIONS_BASE64), (character) => character.charCodeAt(0));
  const view = new DataView(bytes.buffer);
  return Array.from({ length: bytes.byteLength / 2 }, (_, index) => view.getUint16(index * 2, true) / 10);
}

/** 2 km square centred on the published Askervein hilltop coordinate. */
export const ASKERVEIN_TERRAIN = {
  siteId: "askervein-copernicus-glo30",
  latitude: 57.1879528,
  longitude: -7.3791861,
  columns: 33,
  rows: 33,
  cellSizeM: 62.5,
  elevationsM: decodeElevations(),
} as const;

export const ASKERVEIN_LAYOUT = {
  rows: 2,
  columns: 2,
  rotorDiameterM: 112,
  hubHeightM: 100,
  crosswindSpacingD: 6,
  downwindSpacingD: 8,
  bearingDeg: 210,
} as const;

export const ASKERVEIN_FIELD_REQUEST = {
  terrain: {
    site_id: ASKERVEIN_TERRAIN.siteId,
    origin_easting_m: 0,
    origin_northing_m: 0,
    columns: ASKERVEIN_TERRAIN.columns,
    rows: ASKERVEIN_TERRAIN.rows,
    cell_size_easting_m: ASKERVEIN_TERRAIN.cellSizeM,
    cell_size_northing_m: ASKERVEIN_TERRAIN.cellSizeM,
    elevations_m: ASKERVEIN_TERRAIN.elevationsM,
  },
  layout: {
    turbine: "vestas-v112-3450",
    rows: ASKERVEIN_LAYOUT.rows,
    columns: ASKERVEIN_LAYOUT.columns,
    crosswind_spacing_d: ASKERVEIN_LAYOUT.crosswindSpacingD,
    downwind_spacing_d: ASKERVEIN_LAYOUT.downwindSpacingD,
    hub_height_m: ASKERVEIN_LAYOUT.hubHeightM,
    // Pinned to the design bearing while the wind turns (D26). Omit it and the server
    // orients the array to whatever direction is being asked about, which presents identical
    // geometry at every bearing — no wake relation ever changes, and T3 has no answer.
    orientation_bearing_deg: ASKERVEIN_LAYOUT.bearingDeg,
    origin_easting_m: 1000,
    origin_northing_m: 1000,
  },
  wind: { bearing_deg: ASKERVEIN_LAYOUT.bearingDeg, speed_ms: 10, turbulence_intensity: 0.08 },
  volume: { levels: 8, top_elevation_m: 500 },
};
